FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install --production
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY . .
RUN npm run build
FROM nginx:stable
COPY --from=build /app/dist/budget-planner /usr/share/nginx/html
EXPOSE 4200
CMD ["npm", "start"]