# Use Node.js as the build stage
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Use a separate stage for the final image
FROM nginx:stable
# Copy the production build files from the build stage
COPY --from=build /app/dist/budget-planner /usr/share/nginx/html
# Expose port 4200 (the port your Angular app is running on)
EXPOSE 80